spring:
  flyway:
    placeholders:
      DB_USERNAME: cybriabankuser

db:
  jdbcUrl: jdbc:postgresql://localhost:5432/db
  username: cybriabankuser
  password: cybriabankuser
  ownerUserName: cybriabankowner
  ownerPassword: cybriabankowner


