#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD' LOGIN;
    COMMENT ON ROLE $APP_DB_USER IS 'Test';
EOSQL